# Welcome to Jekyll!

# Site settings
title: "9XD 블로그"

baseurl: "/"
url: "http://9XD.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  last_name: '9X년생'
  first_name: '개발자 모임'

  email: 'jayjinjay@gmail.com'
  facebook_username: 'groups/1565641083693087'
  head_img: 'static/img/landing/9xd.png'

# landing page
landing:
  home: 'Home'
  about: 'About'
  meetup: 'Meet Up'
  projects: 'Project'
  blog: 'Blog'
  contact: 'Contact'

# my projects
project:
  meetup:
    name: 'Meet Up'
    url: '/blog/meetup'
    img: 'static/img/landing/9x_meetup.jpg'
  blog:
    name: 'Blog'
    url: '/blog/'
    img: 'static/img/landing/post.jpg'
  undefined:
    name: 'Undefined'
    url: '/'
    img: 'static/img/landing/question_mark.png'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  appid: cysfY7ULn
  conf: prod_861928934cecb7a18e15bedaed9dae29

# google analytics
ga:
  id: UA-79196391-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge